### PR TITLE
Development

### PR DESCRIPTION
**Pull request by gowrisankarvs**
Modified System, Chassis, Linecard and interface rules according to rule guidelines.
 - Removed caps
- Removed under scores
- Modified regular expressions due to influx db issues
- Increased sensor frequencies in all rule files due to performance best practices which led to modification of trigger frequency and time-ranges.

### CODE REVIEW

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by gvarao** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Pull request merged**
