### PR TITLE
Removed zero suppression

### PR DESCRIPTION
**Pull request by vvikramb**
Removed zero-suppression from fields in "hardware.chassis/check-fan-state-rpm" rule.

### CODE REVIEW

**Comment by vvikramb** [comment]
Jenkins please retry a build

**Comment by vvikramb** [comment]
Jenkins please retry a build

**Comment by vvikramb** [comment]
Jenkins please retry a build

**Comment by sharanyab16** [comment]
Jenkins please retry a build

**Comment by sharanyab16** [comment]
Jenkins please retry a build

**Pull request closed without merging**
