### PR TITLE
Setting up my git environment

### PR DESCRIPTION
**Pull request by vpomuran**
Setting up my git environment

### CODE REVIEW

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by vpomuran** [comment]
Hello ayushgithub,
 I was following the readme file and the last step there is "From your fork open a pull request to the development branch".
 And yes I am a Juniper employee. I do not have much git experience so I just followed the instructions. I was not planning to commit anything at this moment.

**Comment by ayushgithub** [comment]
Only Juniper employees can contribute to                        juniper_official folder. If you are one follow the                        steps mentioned in the README else, contribute to the                        community_supplied directory. Make the necessary                        changes and commit again.

**Comment by ayushgithub** [comment]
@vpomuran - There is no problem. Just gohead and close this pull request when you are done experimenting.

**Pull request closed without merging**
