### PR TITLE
updated chip.yml file and related yml files. Also updated software-version.rule and system-cpu-load-average.rule

### PR DESCRIPTION
**Pull request by gowrisankarvs**
chip.yml and related files updated with following changes according to #131:-
   - All missing yml files are added
   - Modified the variable names from _ to -.
 
online-fpc.playbook, online-fpc.rule, online_fpc.py and online_fpc.yml are added to collected online FPC information according to #133.
ithrottle.rule Variable names change required according to #152 
system-cpu-load-average rule table name needs to be modified according to #153

### CODE REVIEW

**Comment by gowrisankarvs** [comment]
Please rerun it

**Comment by gowrisankarvs** [comment]
Please rerun it

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by ayushgithub** [comment]
jenkins please retry a build

**Comment by gowrisankarvs** [comment]
please rerun

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Comment by gowrisankarvs** [comment]
please rerun

**Comment by gowrisankarvs** [comment]
please rerun

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Comment by gowrisankarvs** [comment]
please retry a build

**Comment by gowrisankarvs** [comment]
jenkins please retry a build

**Pull request merged**
